/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Optimizer.GUI;

import Optimizer.Optimizer;
import Optimizer.Store;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author JDiercks14
 */
public class OptimEvent extends javax.swing.JPanel {
   
    //True = Width
    //False = Height
    public static boolean WidthOrHeight = true;
    
    protected ArrayList<String> storeNumberList;
    
    private Optimizer optimizer;
    
    /**
     * Creates new form OptimEvent
     */
//   public static void main(String[] args) {
//    java.awt.EventQueue.invokeLater(new Runnable() {
//          public void run() {
//               OptimEvent frame = new OptimEvent();
//               frame.setVisible(true);
//          }
//    });                
//} 
//    public static void main(String[] argv){
//           boolean WidthOrHeight = true;
//    }
//    
    
    
    public OptimEvent(Optimizer optimizerObj) throws SQLException {
        initComponents();  
        
        optimizer = optimizerObj;
        
        // Initialize and assign store number list and labels
        storeNumberList = optimizer.getStoreNumberList();

        // Assign store number combo box information and adds list information
//        storeNumberCB = new JComboBox(storeNumberList.toArray());
//        storeNumberCB.setEditable(true);
//        AutoCompleteDecorator.decorate(storeNumberCB);
        
//        jComboBox1.addItem("hhhhhh");
//        jComboBox1.addI
        jComboBox1.setModel(new DefaultComboBoxModel(storeNumberList.toArray()));
        AutoCompleteDecorator.decorate(jComboBox1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_buttons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sortWidth = new javax.swing.JRadioButton();
        sortHeight = new javax.swing.JRadioButton();
        optimizationCall = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        group_buttons.add(sortWidth);
        sortWidth.setSelected(true);
        sortWidth.setText("Sort by Width");
        sortWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortWidthActionPerformed(evt);
            }
        });

        group_buttons.add(sortHeight);
        sortHeight.setText("Sort By Height");
        sortHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortHeightActionPerformed(evt);
            }
        });

        optimizationCall.setText("Optmize by Constraints");
        optimizationCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimizationCallActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Optimizer");

        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Select Store to Optimize:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sortWidth)
                        .addGap(18, 18, 18)
                        .addComponent(sortHeight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(optimizationCall)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortWidth)
                    .addComponent(sortHeight))
                .addGap(18, 18, 18)
                .addComponent(optimizationCall)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sortHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortHeightActionPerformed
        WidthOrHeight = false;
//        printOut.setText(Boolean.toString(WidthOrHeight));
        
    }//GEN-LAST:event_sortHeightActionPerformed

    private void optimizationCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimizationCallActionPerformed
        String storeNum = (String) jComboBox1.getSelectedItem();
        String storeName = "";
        String report = "";
        int totalUnits = 0;
        try {
            Store store = optimizer.getStore(storeNum);
            storeName = store.getStoreName();
            totalUnits = store.getTotalUnits();
            report = optimizer.generateReport(WidthOrHeight, storeNum, storeName, totalUnits);
            ReportGUI reportGUI = new ReportGUI();
            reportGUI.setVisible(true);
            reportGUI.displayReport(report);
//            printOut.setText(report);
        } catch (SQLException ex) {
            Logger.getLogger(OptimEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_optimizationCallActionPerformed

    private void sortWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortWidthActionPerformed
        WidthOrHeight = true;        
//        printOut.setText(Boolean.toString(WidthOrHeight));
                
    }//GEN-LAST:event_sortWidthActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //pass optimizer as a permater
        //they all pass as permaiter then call list
        //Make get store method ,, reteave store based on what was created ,, used to create object        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group_buttons;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton optimizationCall;
    private javax.swing.JRadioButton sortHeight;
    private javax.swing.JRadioButton sortWidth;
    // End of variables declaration//GEN-END:variables
}
